### ISSUE TITLE
Feature request: Events that span multiple dates

### ISSUE THREAD

**Issue by Xiaoming94** [cthit/chalmersit-rails#347] opened 2018-03-27 10:15 UTC
As of now, It's impossible to span an event across multiple dates, at least in the GUI of the homepage.

This feature would be nice to have since for instance if you are posting an event about LAN-parties that spans a whole weekend

**Comment by malmers** [comment] 2018-03-27 10:34
Duplicate of #97

**Closed by malmers** 2018-03-27 10:34 UTC
