### ISSUE TITLE
Error flashes don't take enough space

### ISSUE THREAD

**Issue by kirayatail** [cthit/chalmersit-rails#65] opened 2016-05-20 08:56 UTC
<img width="1742" alt="skarmavbild 2016-05-20 kl 10 56 02" src="https://cloud.githubusercontent.com/assets/1055844/15422561/836ce7c6-1e79-11e6-976e-69251e26baab.png">

**Comment by Vilddjur** [comment] 2016-05-20 10:10
duplicate of #60

**Closed by Vilddjur** 2016-05-20 10:10 UTC
Labels: bug, sämst
