### ISSUE TITLE
Problem uploading file with new post

### ISSUE THREAD

**Issue by hjorthjort** [cthit/chalmersit-rails#90] opened 2016-10-05 10:31 UTC
- Problem uploading file, uploaded a .png file which was working on chalmers.it, beta.chalmers.it interpreted it as not "jpeg/png...".
- When trying with the same picture later, it pasted it as code into the body and deleted whatever was there before.

_Split from #87_

**Comment by Kerp1** [comment] 2016-10-07 23:11
I tried to reproduce this but it seemed to work for me, the correct markup to display the picture was appended to the post at least.

**Comment by Vilddjur** [comment] 2016-11-17 09:48
Im setting the label to low for now.

**Comment by Vilddjur** [comment] 2016-12-01 10:27
second part fixed asof 69a50e9c90ec262c739aab67212f0a54879ea48b

**Comment by Vilddjur** [comment] 2017-01-16 09:41
I am closing this since this problem seems to not be reproducible

**Closed by Vilddjur** 2017-01-16 09:41 UTC
Labels: bug, low
