### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by SSundstrom** [cthit/chalmersit-rails#288] opened 2017-05-15 12:50 UTC
https://cthit.slack.com/files/sune/F5EB9ESUE/pasted_image_at_2017_05_15_14_47.png

The box for upcoming events might be a bit bigger or need some other constraints.

**Comment by Kalior** [comment] 2017-05-15 13:45
Thanks for the bug report! But is a duplicate of #166, closing.

**Closed by Kalior** 2017-05-15 13:45 UTC
