### ISSUE TITLE
Make it easier to display committee/societies board members information

### ISSUE THREAD

**Issue by Xiaoming94** [cthit/chalmersit-rails#261] opened 2017-03-08 13:51 UTC
Like in pre-rails days. See for instance: [https://old.chalmers.it/sektionen/kommitteer/digit/](https://old.chalmers.it/sektionen/kommitteer/digit/)

**Comment by malmers** [comment] 2017-03-08 13:58
duplicate of #216

**Closed** 2017-03-08 14:02 UTC
Labels: feature
